name: DockerBuild

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"


      - name: set up buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build (and publish) main image
        env:
          # fork friendly ^^
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
        run: |
          [[ ! "$VERSION" =~ [0-9] ]] && export VERSION=${{ steps.prepare.outputs.sha_short }}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=$VERSION \
            --push \
            -t ${DOCKER_REPO:-louisehong/arm64}:$VERSION \
            -t ${DOCKER_REPO:-louisehong/arm64}:latest \
            -f Dockerfile.hub \
            .
